### ISSUE TITLE
Version 0.2 not registered with the package registry

### ISSUE THREAD

**Issue by arnief3** [plut/ConstructiveGeometry.jl#26]
add ConstructiveGeometry
results in version 0.1

Looking forward to OpenSCAD + Julia!

**Comment by plut** [comment]
I am currently working on a major rewrite of the package (I replaced most of my own 3d code by calls to `libigl`, having learned the hard way about inexact geometry...). Most of it is done (you can already explore the online documentation for a preview...). Expect something in the next few days/weeks once it becomes stable enough (there are still a large number of bugs to fix).

**Comment by plut** [comment]
v0.2.0 is up.
