### ISSUE TITLE
Increasing number of steps in extrude_rotation

### ISSUE THREAD

**Issue by jwscook** [plut/ConstructiveGeometry.jl#27]
Hello. Could you tell me how to increase the number of steps taken `extrude_rotate` a polygon so that the step size in angle is smaller please?

```
s = rotate_extrude(360) * polygon([[1, 0], [2, 0], [2, 1], [1, 1], [1, 0]])
stl("file.stl", s)
```

gives

![image](https://user-images.githubusercontent.com/15519866/154251381-aa955cc7-92c6-4ff6-a0f2-ec51cdb718e5.png)

which has 10 faces on the outer diameter and 8 on the inner. How can I make these numbers arbitrarily high?

**Comment by plut** [comment]
You can prefix with `set_parameters(atol=..., rtol=...)` (making both values small). See https://plut.github.io/ConstructiveGeometry.jl/dev/meshing/#Parameters . A bit below this is the exact formula for the number of vertices in a circle; the same also applies to `rotate_extrude`.

**Comment by jwscook** [comment]
Perfect - thank you. For future readers, here is the fix:

```julia
using ConstructiveGeometry
s = set_parameters(atol=0, rtol=1e-3) * rotate_extrude(360) * polygon([[1, 0], [2, 0], [2, 1], [1, 1], [1, 0]])
stl("file.stl", s)
```

**Comment by plut** [comment]
(By the way, 360 degrees is the default value, so `rotate_extrude()` is sufficient here. Also, in the latest versions, this package uses `FileIO`, so the recommended way to export is by using `save("file.stl", s)`; "file.ply" also works if you prefer that (slightly more efficient) format.)
